name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and lint tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Check Ansible syntax
        run: ansible-playbook --syntax-check playbook.yml

      - name: Lint Ansible playbook
        run: ansible-lint playbook.yml
